export const COMMAND_ERROR_CODES = {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  MISSING_ARGUMENT: 'MISSING_ARGUMENT',
  MANIFEST_NOT_FOUND: 'MANIFEST_NOT_FOUND',
  MANIFEST_INVALID: 'MANIFEST_INVALID',
  TEMPLATE_VARIABLE_MISSING: 'TEMPLATE_VARIABLE_MISSING',
  MISSING_PACKAGE_MANIFEST: 'MISSING_PACKAGE_MANIFEST',
  MISSING_INSTALL_PLAN: 'MISSING_INSTALL_PLAN',
  INSTALL_CONFLICT: 'INSTALL_CONFLICT',
  PATH_ESCAPE: 'PATH_ESCAPE',
  LOCK_TIMEOUT: 'LOCK_TIMEOUT',
  SCAN_FAILED: 'SCAN_FAILED',
  DOCTOR_FAILED: 'DOCTOR_FAILED',
  LIST_FAILED: 'LIST_FAILED',
} as const;

export type CommandErrorCode = typeof COMMAND_ERROR_CODES[keyof typeof COMMAND_ERROR_CODES];
