export const COMMAND_ERROR_CODES = {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  MISSING_ARGUMENT: 'MISSING_ARGUMENT',
  MANIFEST_NOT_FOUND: 'MANIFEST_NOT_FOUND',
  MANIFEST_INVALID: 'MANIFEST_INVALID',
  MANIFEST_ALREADY_EXISTS: 'MANIFEST_ALREADY_EXISTS',
  UNSUPPORTED_MANIFEST_VERSION: 'UNSUPPORTED_MANIFEST_VERSION',
  TEMPLATE_VARIABLE_MISSING: 'TEMPLATE_VARIABLE_MISSING',
  MISSING_PACKAGE_MANIFEST: 'MISSING_PACKAGE_MANIFEST',
  MISSING_INSTALL_PLAN: 'MISSING_INSTALL_PLAN',
  INSTALL_CONFLICT: 'INSTALL_CONFLICT',
} as const;

export type CommandErrorCode = typeof COMMAND_ERROR_CODES[keyof typeof COMMAND_ERROR_CODES];
